
  SLACK_FAILURE:         '#ff0000'
  SLACK_SUCCESS:         '#00ff00'
  SLACK_ICON:            https://raw.githubusercontent.com/DFE-Digital/get-into-teaching-api/master/.github/image.png?size=48
  SLACK_USERNAME:        GiT Workflows
  SLACK_FOOTER:          Get School Experience Prototype
  DOCKER_REPOSITORY:     ghcr.io/dfe-digital/get-schoolexperience-prototype
  DOMAIN:                london.cloudapps.digital
  APPLICATION:           Get School Experience Prototype
  REVIEW_APPLICATION:    review-get-schoolexperience-prototype
  PAAS_APPLICATION_NAME: get-schoolexperience-prototype
